### PR TITLE
Publish trainer base image to quay.io

### PR DESCRIPTION
**Pull request by szaher**
**What this PR does / why we need it**:
Added github action to publish trainer base image to quay.io/opendatahub/trainer-base-image 

**Which issue(s) this PR fixes** _(optional, in `Fixes #<issue number>, #<issue number>, ...` format, will close the issue(s) when PR gets merged)_:

Fixes: https://issues.redhat.com/browse/RHOAIENG-13199 

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/training/) included if any changes are user facing

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Comment by sutaakar** [comment]
@szaher Is this PR good to merge or do you plan more changes there?

**Review by astefanutti — COMMENTED** [review]
The Dockerfile is being moved to opendatahub-io/training-operator#16 so the GH actions workflow should follow there. An option is to skip GH actions workflow and solely rely on Konflux.

cc @Fiona-Waters

**Comment by Fiona-Waters** [comment]
> The Dockerfile is being moved to #16 so the GH actions workflow should follow there. An option is to skip GH actions workflow and solely rely on Konflux.
> 
> cc @Fiona-Waters

If we don't use GH actions for the other images then probably we can follow the same path for this one. At the moment I am just pushing to my quay.io for testing purposes.

**Pull request closed without merging**
