### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by Fiona-Waters**
**What this PR does / why we need it**:

This PR updates the OWNER file to reflect current contributors.

### CODE REVIEW

**Review by astefanutti — COMMENTED** [review]
Do we want to use the patch convention we have for other forks, and add the `CARRY:` prefix to the commit message?

**Comment by Fiona-Waters** [comment]
> Do we want to use the patch convention we have for other forks, and add the `CARRY:` prefix to the commit message?

Absolutely. Apologies that I missed this. I noticed that some other commits were also missing this so updated and synced the repos.

**Review by astefanutti — APPROVED** [review]

**Comment by astefanutti** [comment]
> > Do we want to use the patch convention we have for other forks, and add the `CARRY:` prefix to the commit message?
> 
> Absolutely. Apologies that I missed this. I noticed that some other commits were also missing this so updated and synced the repos.

Awesome, thanks a lot @Fiona-Waters!

**Pull request merged**
